name: Build Windows Installer v1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '26'
        cache: 'npm'

    - name: Install dependencies and compile app
      run: |
        npm ci
        npm run build

    - name: Compile Installer with Inno Setup
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer-config.iss
      shell: powershell

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: Output/*.exe
